// Isolated Chromium acceptance. Every message, permission and send is synthetic.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const ROOT=path.resolve(process.env.FRONTEND_ROOT||path.join(__dirname,'../app/web/pet')),OUT=path.resolve(__dirname,'../.runtime/messages-ui-smoke');
const CHROME=process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe';
fs.mkdirSync(OUT,{recursive:true});
const requests=[],errors=[];let sends=0,unknown=false,enabled=true,missingDossiers=false,missingContext=false,missingNames=false,failTopic=false,mediaFixtures=false;const renames=new Map();
const receipts=new Map(),policies=new Map(),received='2026-10-05T01:00:00Z';
const conversations=Array.from({length:55},(_,i)=>({conversation_key:'conversation_'+i,platform:'qq',account_id:'123456',conversation_type:'group',conversation_id:String(90000+i),display_name:i===0?'项目协作群':'资料群 '+i,record_enabled:true,analysis_enabled:false,media_enabled:true,min_interval_seconds:300,max_wait_seconds:900,revision:2,message_count:120+i}));
const metadata=item=>({...item,display_name:renames.get(item.conversation_key)||(item.conversation_key==='conversation_0'?'项目协作':'资料群 '+item.conversation_id),user_alias:renames.get(item.conversation_key)||(item.conversation_key==='conversation_0'?'日常协作':null),revision:1});
const msg=(id,seq,text='测试原文',extra={})=>({message_id:id,seq,provider_message_id:id,conversation_key:'conversation_0',sender_id:'88888',sender_name:'参与者甲',text,sent_at:1791158400+seq,received_at:1791158400+seq,...extra});
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64');
const sendJSON=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));};
const server=http.createServer(async(req,res)=>{
 const url=new URL(req.url,'http://localhost');let chunks=[];for await(const chunk of req)chunks.push(chunk);const body=Buffer.concat(chunks);
 if(url.pathname.startsWith('/plugins/')){
  requests.push({path:url.pathname,query:url.search,method:req.method,auth:req.headers.authorization,cookie:req.headers.cookie,intent:req.headers['x-lka-ui-intent'],body:body.length<100000?body.toString():''});
  const p=url.pathname.replace('/plugins/message-reading','').replace('/plugins/qq-ui','');
  if(url.pathname.startsWith('/plugins/qq-ui')){
   if(p==='/status')return sendJSON(res,200,{enabled:true,ready:true,send_enabled:enabled,account_id:'123456',reading_paired:true});
   if(p.startsWith('/groups/')){const id=p.split('/').pop();return sendJSON(res,200,{account_id:id==='90002'?'wrong-account':'123456',group_id:id,group_name:'QQ 自动群名 '+id,cached:true,stale:false});}
   if(p==='/capabilities')return sendJSON(res,200,{image_max_bytes:20971520,video_max_bytes:209715200});
   if(p.startsWith('/conversations/')){if(req.method==='PUT')policies.set(p,JSON.parse(body));return sendJSON(res,200,policies.get(p)||{receive_enabled:true,send_enabled:true});}
   if(p==='/messages')return sendJSON(res,200,{messages:[],next_cursor:Number(url.searchParams.get('after')),has_more:false});
   if(p==='/messages/send'){
    const value=JSON.parse(body);sends++;const receipt={key:value.idempotency_key,state:'accepted',message_id:'sent_'+sends,error:null,created_at:received};receipts.set(value.idempotency_key,receipt);
    if(unknown)return sendJSON(res,503,{detail:'gateway_unavailable'});
    return setTimeout(()=>sendJSON(res,200,receipt),500);
   }
   if(p.startsWith('/sends/'))return sendJSON(res,200,receipts.get(p.split('/').pop())||{state:'unknown'});
   if(p.startsWith('/media/'))return sendJSON(res,201,{id:'a'.repeat(64),kind:p.split('/').pop(),mime:'image/png',size:body.length,sha256:'b'.repeat(64)});
   if(p==='/stickers')return sendJSON(res,200,{stickers:[{emoji_id:'123_0_emoji'}]});
  }
  if(p==='/messages/conversations')return sendJSON(res,200,{conversations:conversations.slice(Number(url.searchParams.get('offset')||0),Number(url.searchParams.get('offset')||0)+50),next_offset:Number(url.searchParams.get('offset')||0)===0?50:null});
  if(p==='/messages/policies'){if(req.method==='PUT'){const value=JSON.parse(body),item=conversations.find(v=>v.conversation_id===value.conversation_id);item.display_name=value.display_name;item.revision++;renames.set(item.conversation_key,value.display_name);return sendJSON(res,200,{policy:item});}return sendJSON(res,200,{policies:conversations.slice(0,2)});}
  if(p==='/messages/conversations/resolve')return sendJSON(res,200,{matches:[metadata(conversations[0])],ambiguous:false,has_more:false});
  if(p.endsWith('/metadata')){if(missingNames)return sendJSON(res,404,{});const item=conversations.find(v=>p.includes('/'+v.conversation_key+'/'));if(req.method==='PATCH'){renames.set(item.conversation_key,JSON.parse(body).user_alias);return sendJSON(res,200,{...metadata(item),user_alias:JSON.parse(body).user_alias,revision:2});}return sendJSON(res,200,metadata(item));}
  if(p.endsWith('/history')&&mediaFixtures)return sendJSON(res,200,{messages:[msg('media_image',10,'',{content_kind:'unsupported',ui_content_parts:[{kind:'image',ordinal:0}]}),msg('media_video',11,'',{attachments:[{attachment_id:'old_video',kind:'video',state:'expired',file_name:'clip.mp4'}]}),msg('media_face',12,'',{ui_content_parts:[{kind:'face',ordinal:0,id:'178'}]}),msg('media_sticker',13,'看看这个',{ui_content_parts:[{kind:'mface',ordinal:1}]}),msg('media_voice',14,'',{content_parts:[{kind:'unsupported'}],ui_content_parts:[{kind:'record',ordinal:0}]}),msg('media_unknown',15,'  ',{content_kind:'unsupported'}),msg('media_url',16,'[CQ:image,url=https://private.invalid/token=SECRET]',{content_kind:'unsupported'})],next_before_seq:null});
  if(p.endsWith('/history')&&missingContext){const upper=Number(url.searchParams.get('before_seq')||81),size=Number(url.searchParams.get('limit')||50),values=Array.from({length:80},(_,i)=>msg(i+1===40?'citation_40':'ctx_'+(i+1),i+1,i+1===40?'讨论原文':'历史消息 '+(i+1))).filter(m=>m.seq<upper).reverse();return sendJSON(res,200,{messages:values.slice(0,size),next_before_seq:values.length>size?values[size-1].seq:null});}
  if(p.endsWith('/history'))return sendJSON(res,200,{messages:url.searchParams.has('before_seq')?[msg('older',1,'更早消息')]:[msg('message_2',3,'<img src=x onerror=alert(1)> 原文不会执行'),msg('message_1',2,'项目讨论：附件在这里')],next_before_seq:url.searchParams.has('before_seq')?null:2});
  if(p==='/messages/search')return sendJSON(res,200,{messages:[msg('global_new',1,'较新结果',{conversation_key:'conversation_1',received_at:1791159999}),msg('global_old',99,'较旧结果',{received_at:1791158888})],next_offset:null,has_more:false});
  if(p.endsWith('/context')){if(mediaFixtures)return sendJSON(res,200,{messages:[msg('media_face',12,'',{ui_content_parts:[{kind:'face',ordinal:0,id:'178'}]})],has_more_before:false,has_more_after:false});if(missingContext)return sendJSON(res,404,{});const anchor=p.split('/').at(-2);if(anchor==='citation_40'||anchor.startsWith('ctx_')){const seq=anchor==='citation_40'?40:Number(anchor.slice(4)),before=Number(url.searchParams.get('before')),after=Number(url.searchParams.get('after')),values=Array.from({length:80},(_,i)=>msg(i+1===40?'citation_40':'ctx_'+(i+1),i+1,i+1===40?'讨论原文':'历史消息 '+(i+1))).filter(m=>m.seq>=seq-before&&m.seq<=seq+after);return sendJSON(res,200,{messages:values,anchor_message_id:anchor,has_more_before:values[0].seq>1,has_more_after:values.at(-1).seq<80});}return sendJSON(res,200,{messages:[msg('before',1,'前文'),msg('message_1',2,'上下文锚点'),msg('after',3,'后文')],anchor_message_id:'message_1',gap_before:true,gap_after:false,has_more_before:false,has_more_after:false});}
  if(p==='/messages/attachments')return sendJSON(res,200,{attachments:[{attachment_id:'attachment_1',internal_message_id:'message_1',kind:'image',state:'cached',file_name:'sample.png'}],next_offset:null});
  if(p.endsWith('/content')){res.writeHead(200,{'content-type':'image/png','content-length':PNG.length});return res.end(PNG);}
  if(p.endsWith('/summary'))return sendJSON(res,200,{summary:{summary:'旧接口摘要',covered_seq:1,pending_count:0}});
  if(p.endsWith('/coverage'))return sendJSON(res,200,{coverage:{analysis_baseline_floor_seq:100,analysis_watermark_seq:150,excluded_history_count:99,pending_messages:4}});
  if(p==='/messages/reading/overview')return sendJSON(res,200,{coverage:[{conversation_key:'conversation_0',capture_mode:'live',pending_messages:4}],topics:[],insights:[],unseen_count:2});
  if(p==='/messages/reading/topics')return sendJSON(res,200,{topics:Array.from({length:25},(_,i)=>({topic_id:'topic_'+i,conversation_key:'conversation_0',title:'讨论主题 '+i,summary:'团队正在讨论项目安排与待解决问题。',heat:{participant_count:0,total_participant_count:3,recent_participant_count:0}})),next_cursor:null});
  if(/^\/messages\/reading\/topics\/topic_\d+$/.test(p)){if(failTopic)return sendJSON(res,503,{});return setTimeout(()=>sendJSON(res,200,{topic:{title:'讨论主题详情',summary:'原文支持的主题摘要\n\n- **待办**：确认安排',conversation_key:'conversation_0'}}),350);}
  if(/^\/messages\/reading\/topics\/topic_\d+\/sources$/.test(p))return sendJSON(res,200,{sources:[msg('citation_40',40,'讨论原文'),...(mediaFixtures?[msg('evidence_sticker',41,'',{ui_content_parts:[{kind:'sticker',ordinal:0}]})]:[])],next_cursor:null});
  if(p==='/messages/reading/dossiers'){if(missingDossiers)return sendJSON(res,404,{});return sendJSON(res,200,{dossiers:[{conversation_key:'conversation_0',sender_id:'88888',sender_name:'人物甲',claim_count:1,source_count:2}],next_offset:null});}
  if(p==='/messages/reading/dossiers/conversation_0/88888')return sendJSON(res,200,{sender_name:'人物甲的新昵称',claims:[{text:'有原文支持的观察',basis:'explicit',quote:'证据引文'}],machine_notes:[{text:'未采纳的推断',proposed_basis:'uncertain',status:'rejected',rejection_reason:'证据不足',expires_at:'2026-10-05T03:00:00Z'}],source_count:2,updated_at:received,next_offset:null});
  if(p.endsWith('/sources'))return sendJSON(res,200,{sources:[msg('evidence_1',3,'档案证据')],next_offset:null});
  if(p==='/background/services/message-reading')return sendJSON(res,200,{paused:false,revision:1,enabled:true,budget:{used_tokens:12000}});
  if(p==='/background/config')return sendJSON(res,200,{revision:1,active:{message_history:{background_model:'model-a'}},desired:{message_history:{background_client_name:'test-client',background_model:'model-a'}},restart_required:false});
  if(p==='/messages/reading/profile')return sendJSON(res,200,{revision:1,self_ids:{},aliases:[],keywords:[]});
  if(p==='/agent/models')return sendJSON(res,200,{clients:[{name:'test-client',models:['model-a','model-b']}]});
  if(p==='/messages/reading/participants')return sendJSON(res,200,{participants:[{conversation_key:'conversation_0',sender_id:'77777',sender_name:'参与者群名片',summary:'活跃画像',revision:1}],next_cursor:null});
  if(p==='/messages/reading/participants/conversation_0/77777')return sendJSON(res,200,{conversation_key:'conversation_0',sender_id:'77777',sender_name:'参与者最新昵称',summary:'活跃画像详情',revision:1});
  if(p==='/plugins/qq-reader/status'||url.pathname==='/plugins/qq-reader/status')return sendJSON(res,200,{plugin_id:'qq_reader',enabled:true,connection_state:'connected',sync_state:'idle'});
  return sendJSON(res,404,{detail:'not_mocked'});
 }
 let file=path.resolve(ROOT,'.'+(url.pathname==='/'?'/chat.html':url.pathname));if(!file.startsWith(path.resolve(ROOT)+path.sep)){res.writeHead(403);return res.end();}
 if(url.pathname==='/chat.html'){
  let html=fs.readFileSync(file,'utf8');html=html.replace(/<script src="\.\/(chat|memory|projects)\.js[^>]*><\/script>/g,'');
  html=html.replace('<script src="./qq-reader.js',`<script>window.LkaChatContext={get:()=>({workMode:new URLSearchParams(location.search).get('mode')==='work',backend:'http://unused.invalid',sessionId:'',workspace:''})};window.__lkaMemoryBridgeReceive=()=>{};</script><script src="./qq-reader.js`);
  res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html);
 }
 try{const data=fs.readFileSync(file);res.writeHead(200,{'content-type':({'.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});res.end(data);}catch(_){res.writeHead(404);res.end();}
});
(async()=>{let browser;try{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:CHROME,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
 await page.goto(base+'/chat.html?mode=work');assert.equal(await page.locator('#openMessagesButton svg').count(),1);assert.equal((await page.locator('#openMessagesButton').innerText()).trim(),'');await page.waitForTimeout(100);assert.equal(requests.length,0,'closed center does not load private messages');
 await page.locator('#openMessagesButton').click();await page.waitForFunction(()=>document.querySelector('#mcConversationTitle').textContent==='日常协作');
 assert.equal(sends,0);assert(requests.every(r=>r.method==='GET'),'opening is read-only');
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('.mc-conversation strong')).some(n=>n.textContent==='QQ 自动群名 90001'));assert(!(await page.locator('#mcConversationList').innerText()).includes('QQ 自动群名 90002'),'mismatched account names never applied');assert.equal(await page.locator('#mcConversationTitle').innerText(),'日常协作','manual alias overrides QQ name');
 const timeline=page.locator('#mcTimeline');await timeline.getByText('项目讨论：附件在这里',{exact:true}).waitFor();assert.equal(await timeline.locator('img').count(),0,'untrusted text is inert');
 await timeline.getByRole('button',{name:'查看',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mcTimeline img')?.complete);assert.equal(await timeline.locator('img').count(),1);await page.locator('#mcRefresh').click();await page.waitForTimeout(150);assert.equal(await timeline.locator('img').count(),1,'unchanged status refresh preserves open media');
 await timeline.getByRole('button',{name:'查看上下文'}).first().click();await page.locator('#mcDetailBody').getByText('上下文锚点',{exact:true}).waitFor();assert.equal(await page.locator('#mcMessages').isVisible(),false);await page.locator('#mcDetailBack').click();
 mediaFixtures=true;await page.locator('#mcRefresh').click();await timeline.getByText('编号 178',{exact:true}).waitFor();for(const label of ['图片','视频','QQ 表情','表情包','语音','非文本消息'])assert((await timeline.innerText()).includes(label));assert((await timeline.innerText()).includes('缓存已过期，请在 QQ 中查看'));assert(!(await timeline.innerText()).includes('SECRET'));assert.equal(await timeline.locator('a[href^="https://"]').count(),0);assert(await timeline.locator('.mc-message').evaluateAll(nodes=>nodes.every(n=>n.querySelector('.mc-message-text')?.textContent.trim()||n.querySelector('.mc-media-card'))),'every message has text or a media placeholder');await timeline.locator('.mc-message').filter({hasText:'编号 178'}).getByRole('button',{name:'查看上下文'}).click();await page.locator('#mcDetailBody').getByText('编号 178',{exact:true}).waitFor();await page.locator('#mcDetailBack').click();await page.locator('[data-mc-tab=reading]').click();await page.locator('.reading-tabs [data-tab=topics]').click();await page.locator('.reading-row').first().getByRole('button',{name:'打开详情与原文'}).click();await page.locator('#mcDetailBody .reading-quote').getByText('表情包',{exact:true}).waitFor();await page.locator('#mcDetailBack').click();await page.locator('.reading-tabs [data-tab=overview]').click();await page.locator('.reading-coverage').waitFor();await page.locator('[data-mc-tab=messages]').click();await page.screenshot({path:path.join(OUT,'messages-media-1440x900.png')});await page.setViewportSize({width:430,height:680});assert(await timeline.evaluate(n=>n.scrollWidth<=n.clientWidth+1),'media cards fit narrow viewport');await page.screenshot({path:path.join(OUT,'messages-media-430x680.png')});await page.setViewportSize({width:1440,height:900});mediaFixtures=false;await page.locator('#mcRefresh').click();await timeline.getByText('项目讨论：附件在这里',{exact:true}).waitFor();
 await timeline.getByRole('button',{name:'加载更早消息'}).click();await timeline.getByText('更早消息',{exact:true}).waitFor();
 await page.locator('#mcQuery').fill('项目');await page.locator('#mcSearchAll').check();await page.locator('.mc-filter-details summary').click();await page.locator('#mcSender').fill('甲');await page.locator('#mcSince').fill('2026-10-05T08:00');await page.locator('#mcSearchForm button[type=submit]').click();await timeline.getByText('较新结果',{exact:true}).waitFor();
 assert((await timeline.innerText()).indexOf('较新结果')<(await timeline.innerText()).indexOf('较旧结果'),'global results use reception order, not local seq');
 const search=requests.findLast(r=>r.path.endsWith('/messages/search'));assert(new URLSearchParams(search.query).get('since').match(/^\d+$/));assert.equal(new URLSearchParams(search.query).get('sender'),'甲');
 await page.locator('#mcClearSearch').click();await timeline.getByText('项目讨论：附件在这里',{exact:true}).waitFor();
 await page.locator('[data-mc-tab=people]').click();await page.locator('#mcPeopleList strong').getByText('人物甲',{exact:true}).waitFor();assert((await page.locator('#mcPeopleList').innerText()).includes('QQ 88888'));await page.getByRole('button',{name:'查看档案与证据'}).click();await page.locator('#mcPersonDetail').getByText('档案证据',{exact:true}).waitFor();assert((await page.locator('#mcPersonDetail').innerText()).includes('未采纳的模型记录'));assert((await page.locator('#mcPersonDetail').innerText()).includes('未采纳原因：证据不足'));assert.equal(await page.locator('#mcPersonDetail h3').innerText(),'人物甲的新昵称');assert.equal(await page.locator('#mcDetailTitle').innerText(),'人物甲的新昵称');
 await page.locator('[data-mc-tab=reading]').click();await page.waitForFunction(()=>document.querySelector('.reading-coverage'));assert.equal(await page.locator('.reading-filters select').inputValue(),'conversation_0');assert(!(await page.locator('.reading-coverage>strong').innerText()).includes('conversation_0'));
 await page.locator('.reading-tabs [data-tab=participants]').click();await page.locator('.reading-row strong').getByText('参与者群名片',{exact:true}).waitFor();assert((await page.locator('.reading-row').innerText()).includes('QQ 77777'));await page.getByRole('button',{name:'查看画像与证据'}).click();await page.locator('#mcDetailTitle').getByText('参与者最新昵称',{exact:true}).waitFor();await page.locator('#mcDetailBody').getByText('活跃画像详情',{exact:true}).waitFor();assert.equal(await page.locator('#mcDetailTitle').innerText(),'参与者最新昵称');assert((await page.locator('#mcDetailBody').innerText()).includes('QQ 77777'));await page.locator('#mcDetailBack').click();await page.locator('.reading-tabs [data-tab=overview]').click();await page.locator('.reading-coverage').waitFor();


 await page.locator('.reading-tabs [data-tab=topics]').click();await page.locator('.reading-row').first().getByText('累计参与：3；近24小时：0；变化：未标注',{exact:true}).waitFor();await page.locator('.reading-row').last().getByRole('button',{name:'打开详情与原文'}).click();await page.locator('#mcDetailPanel').waitFor();await page.locator('#mcDetailBody').getByText('正在读取详情与原文…',{exact:true}).waitFor();assert.equal(await page.locator('#mcReading').isVisible(),false,'detail uses a dedicated route');await page.locator('#mcDetailBody').getByText('讨论原文',{exact:true}).waitFor();
 assert.equal(await page.locator('#mcDetailBody .markdown-body strong').innerText(),'待办');await page.screenshot({path:path.join(OUT,'reading-detail-1440x900.png')});await page.locator('#mcDetailBody').getByRole('button',{name:'查看前后消息'}).click();await page.locator('.mc-context-thread .mc-anchor').waitFor();assert((await page.locator('.mc-context-thread').innerText()).includes('历史消息 30'));await page.locator('.mc-context-controls').getByRole('button',{name:'更早消息',exact:true}).click();await page.locator('.mc-context-thread').getByText('历史消息 5',{exact:true}).waitFor();await page.locator('.mc-context-controls').getByRole('button',{name:'较新消息',exact:true}).click();await page.locator('.mc-context-thread').getByText('历史消息 75',{exact:true}).waitFor();assert.equal(await page.locator('.mc-context-thread .mc-anchor').count(),1);await page.locator('.mc-context-controls').getByRole('button',{name:'更早消息',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.mc-context-thread')?.textContent.includes('历史消息 1'));assert.equal(await page.locator('.mc-context-controls').getByRole('button',{name:'更早消息',exact:true}).isDisabled(),true);await page.locator('.mc-context-controls').getByRole('button',{name:'回到目标消息',exact:true}).click();await page.locator('.mc-anchor-label').waitFor();await page.screenshot({path:path.join(OUT,'message-context-1440x900.png')});await page.setViewportSize({width:430,height:680});await page.waitForTimeout(100);assert(await page.locator('#mcDetailBody').evaluate(n=>n.scrollWidth<=n.clientWidth+1),'context fits narrow viewport');await page.screenshot({path:path.join(OUT,'message-context-430x680.png')});await page.setViewportSize({width:1440,height:900});await page.locator('#mcDetailBack').click();await page.locator('#mcDetailBody').getByText('讨论原文',{exact:true}).waitFor();await page.locator('#mcDetailBack').click();assert.equal(await page.locator('#mcReading').isVisible(),true);assert(await page.locator('#mcReading').evaluate(n=>n.scrollTop)>500,'return preserves list position');
 failTopic=true;await page.locator('.reading-row').last().getByRole('button',{name:'打开详情与原文'}).click();await page.locator('#mcDetailBody').getByRole('button',{name:'重试读取',exact:true}).waitFor();failTopic=false;await page.locator('#mcDetailBody').getByRole('button',{name:'重试读取',exact:true}).click();await page.locator('#mcDetailBody').getByText('讨论原文',{exact:true}).waitFor();
 missingContext=true;await page.locator('#mcDetailBody').getByRole('button',{name:'查看前后消息'}).click();await page.waitForFunction(()=>document.querySelector('.mc-context-hint')?.textContent.includes('历史分页定位'));await page.locator('.mc-context-controls').getByRole('button',{name:'更早消息',exact:true}).click();await page.locator('.mc-context-thread').getByText('历史消息 5',{exact:true}).waitFor();await page.locator('.mc-context-controls').getByRole('button',{name:'较新消息',exact:true}).click();await page.locator('.mc-context-thread').getByText('历史消息 75',{exact:true}).waitFor();await page.locator('#mcDetailBack').click();await page.locator('#mcDetailBack').click();missingContext=false;
 await page.locator('[data-mc-tab=settings]').click();await page.locator('#messageHistoryPanel>summary').click();await page.locator('#messageHistoryList').getByRole('button',{name:'摘要',exact:true}).first().click();await page.locator('#mcDetailBody').getByText('旧接口摘要',{exact:false}).waitFor();assert.equal(await page.locator('#mcSettings').isVisible(),false);await page.locator('#mcDetailBack').click();await page.locator('#messageHistoryList').getByRole('button',{name:'浏览原文',exact:true}).first().click();await page.waitForFunction(()=>document.querySelector('#mcMessages').getClientRects().length>0);await page.locator('[data-mc-tab=settings]').click();await page.getByText('阅读后台与显式关注配置',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('.mc-reading-settings select')?.options.length>1);assert.equal(await page.locator('.mc-reading-settings select').count()>=2,true);
 const permission=page.locator('#mcSendingSettings input[type=checkbox]').nth(1);await permission.uncheck();await page.locator('#mcRefresh').click();await page.waitForTimeout(150);assert.equal(await permission.isChecked(),false,'status refresh preserves unsaved permission edits');await permission.check();await page.locator('[data-mc-tab=messages]').click();missingNames=true;await page.locator('#mcRename').click();await page.locator('#mcSheetBody input').fill('工作协作群');await page.locator('#mcSheetBody input').press('Enter');await page.waitForFunction(()=>document.querySelector('#mcConversationTitle').textContent==='工作协作群');const nameWrite=requests.findLast(r=>r.path==='/plugins/message-reading/messages/policies'&&r.method==='PUT');const nameBody=JSON.parse(nameWrite.body);assert.equal(nameBody.display_name,'工作协作群');assert.equal('analysis_enabled' in nameBody,false);assert.equal('media_enabled' in nameBody,false);assert.equal('start_from_now' in nameBody,false);missingNames=false;await page.locator('#mcDraft').fill('第一条草稿');await page.locator('#mcDraft').press('Enter');await page.getByRole('button',{name:'取消',exact:true}).click();assert.equal(sends,0,'cancel never sends');
 await page.locator('#mcDraft').press('Enter');await page.getByRole('button',{name:'确认发送',exact:true}).click();await page.locator('#mcDraft').fill('下一条草稿');await page.waitForFunction(()=>document.querySelector('#mcReceipt').textContent.includes('QQ 已接受'));
 assert.equal(await page.locator('#mcDraft').inputValue(),'下一条草稿');assert.equal(await page.locator('#mcDraft').isDisabled(),false);assert.equal(sends,1);
 await page.locator('#mcDraft').fill('结果待查');unknown=true;await page.locator('#mcDraft').press('Enter');await page.getByRole('button',{name:'确认发送',exact:true}).click();await page.getByRole('button',{name:'查询回执',exact:true}).waitFor();assert.equal(await page.locator('#mcSend').isDisabled(),true);await page.getByRole('button',{name:'查询回执',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mcDraft').value==='');assert.equal(sends,2);assert.equal(await page.locator('#mcSend').isDisabled(),true,'accepted receipt clears unchanged original draft');unknown=false;
 await page.locator('#mcFile').evaluate(input=>input.dataset.kind='image');await page.locator('#mcFile').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:PNG});await page.locator('#mcAttachments').getByText('sample.png',{exact:true}).waitFor();await page.locator('#mcSend').click();await page.getByRole('button',{name:'确认发送',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mcAttachments').textContent==='');assert.equal(sends,3);
 enabled=false;await page.locator('#mcRefresh').click();await page.waitForFunction(()=>document.querySelector('#mcSendHint').textContent.includes('总开关未启用'));await page.locator('#mcDraft').fill('离线也能写草稿');assert.equal(await page.locator('#mcDraft').isDisabled(),false);assert.equal(await page.locator('#mcSend').isDisabled(),true);enabled=true;
 await page.locator('#mcMoreConversations').click();await page.waitForFunction(()=>document.querySelector('#mcConversationCount').textContent==='55 个会话');
 await page.locator('#mcConversationList').hover();await page.mouse.wheel(0,800);await page.waitForTimeout(150);assert(await page.locator('#mcConversationList').evaluate(n=>n.scrollTop)>0,'conversation list scrolls independently');
 await page.screenshot({path:path.join(OUT,'messages-1440x900.png')});
 await page.setViewportSize({width:430,height:680});await page.waitForTimeout(100);const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,send:document.querySelector('#mcSend').getBoundingClientRect().bottom,timeline:document.querySelector('#mcTimeline').getBoundingClientRect().height}));assert(dimensions.scroll<=dimensions.width+1,JSON.stringify(dimensions));assert(dimensions.send<=680,JSON.stringify(dimensions));assert(dimensions.timeline>60,JSON.stringify(dimensions));await page.screenshot({path:path.join(OUT,'messages-430x680.png')});
 // Java callback chain: every JSON call travels through the host bridge.
 await page.evaluate(()=>{window.bridgeCalls=[];window.petBridge={requestMemory(payload){const value=JSON.parse(payload);window.bridgeCalls.push(value);fetch(value.path,{method:value.method,headers:{'Content-Type':'application/json','X-LKA-UI-Intent':'1'},body:value.body||undefined}).then(async r=>window.__lkaMemoryBridgeReceive(value.id,r.status,await r.text()));}};});
 await page.locator('#mcRefresh').click();await page.waitForFunction(()=>window.bridgeCalls.length>=3);assert((await page.evaluate(()=>window.bridgeCalls)).every(v=>/^memory-[a-z0-9]+-\d+$/.test(v.id)&&!v.token));
 await page.locator('#mcClose').click();assert.equal(await page.locator('#messageCenter').isVisible(),false);assert.equal(await page.locator('#openMessagesButton').evaluate(n=>n===document.activeElement),true);
 const before=requests.length;await page.waitForTimeout(500);assert.equal(requests.length,before,'closed center stops polling');
 await page.locator('#openMessagesButton').click();missingDossiers=true;await page.locator('[data-mc-tab=people]').click();await page.locator('#mcPeopleList').getByText('当前后端尚未提供持久档案接口。可在“阅读 → 参与者”查看已有活跃画像。',{exact:true}).waitFor();missingDossiers=false;await page.locator('[data-mc-tab=reading]').click();await page.locator('.reading-tabs [data-tab=overview]').click();await page.waitForTimeout(100);await page.locator('#mcClose').click();const readingBefore=requests.filter(r=>r.path.endsWith('/messages/reading/overview')).length;await page.locator('#openMessagesButton').click();await page.waitForFunction(()=>document.querySelector('#mcReading').getClientRects().length>0);await page.waitForTimeout(200);assert(requests.filter(r=>r.path.endsWith('/messages/reading/overview')).length>readingBefore,'reopening active reading tab refreshes');await page.locator('#mcClose').click();
 assert(requests.every(r=>!r.auth&&!r.cookie),'browser never receives/sends private credentials');assert.equal(errors.length,0,errors.join('\n'));
 console.log(JSON.stringify({result:'PASS',mock_sends:sends,requests:requests.length,screenshots:['messages-1440x900.png','messages-430x680.png','reading-detail-1440x900.png','message-context-1440x900.png','message-context-430x680.png','messages-media-1440x900.png','messages-media-430x680.png'],checks:['closed read isolation','names and pagination','inert message text','media preview','bounded context','search time/author/order','dossier claims vs notes','reading picker','models dropdown','send confirmation','editable pending draft','unknown receipt reconcile','raw upload','disabled draft','sidebar scroll','responsive composer','Java callback routing','focus restore','unsaved settings preserved','old backend fallback','reopened reading refresh','dedicated detail route','immediate loading/retry','nested evidence navigation','back preserves list position','bidirectional context pages','legacy context fallback','legacy rename preserves grants','exhausted context boundary','narrow context','icon entry','legacy history navigation','reading markdown','no credentials','participant and dossier nicknames','secondary QQ identity','detail nickname refresh','QQ group names auto read','manual alias wins','account scoped names','non-text labels and status','media context and evidence','no private media links']},null,2));
 }catch(e){console.error(e.stack||e);process.exitCode=1;}finally{if(browser)await browser.close();server.close();}})();
